In [1]:
import numpy as np

In [2]:
arr = np.array([
    [7, 3, 4],
    [9, 8, 10],
    [15, 18, 1]
])

In [3]:
grad_x = np.gradient(arr, axis=1)
grad_y = np.gradient(arr, axis=0)

magnitude = np.sqrt(grad_x**2, grad_y**2)
directions = np.arctan(grad_y, grad_x) * (180 / np.pi)


print(directions)

hist, _ = np.histogram(directions, range=(0,180), weights=magnitude)

hist.argmax() * (180 / 9)


[[ 63.43494882  78.69006753  80.53767779]
 [ 75.96375653  82.40535663 -56.30993247]
 [ 80.53767779  84.28940686 -83.65980825]]


np.float64(80.0)

In [4]:
arr = np.array([
    [4, 10, 1],
    [3, 8, 18],
    [7, 9, 15]
    
])

In [5]:
grad_x = np.gradient(arr, axis=1)
grad_y = np.gradient(arr, axis=0)

magnitude = np.sqrt(grad_x**2, grad_y**2)
directions = np.arctan(grad_y, grad_x) * (180 / np.pi)


print(directions)

hist, _ = np.histogram(directions, range=(0,180), weights=magnitude)

hist.argmax() * (180 / 9)

[[-45.         -63.43494882  86.63353934]
 [ 56.30993247 -26.56505118  81.86989765]
 [ 75.96375653  45.         -71.56505118]]


np.float64(80.0)

In [6]:
arr = np.array([
    [15, 9, 7],
    [18, 8, 3],
    [1, 10, 4]
])

In [7]:
grad_x = np.gradient(arr, axis=1)
grad_y = np.gradient(arr, axis=0)

magnitude = np.sqrt(grad_x**2, grad_y**2)
directions = np.arctan(grad_y, grad_x) * (180 / np.pi)


print(directions)

hist, _ = np.histogram(directions, range=(0,180), weights=magnitude)

hist.argmax() * (180 / 9)

[[ 71.56505118 -45.         -75.96375653]
 [-81.86989765  26.56505118 -56.30993247]
 [-86.63353934  63.43494882  45.        ]]


np.float64(20.0)